// French 5-letter words — no accents, uppercase, common words
// Split into ANSWERS (common, good puzzle words) and VALID (all accepted guesses)

export const ANSWERS: string[] = [
  // A
  "ABIME","ABORD","ABRIS","ACIDE","ACIER","ADORE","AGILE","AIGLE",
  "AIDER","AIMER","ALBUM","ALLER","ALPIN","AMBRE","AMOUR","ANCRE",
  "ANGLE","ANNEE","APPEL","APRES","ARBRE","ARCHE","ARENE","ARETE",
  "ARGOT","ARMER","AROME","ASTRE","ATOME","AVARE","AVENU","AVEUX",
  "AVION","AVOIR","AYANT",
  // B
  "BAGUE","BALAI","BANDE","BARBE","BARRE","BASER","BATON","BAUME",
  "BAZAR","BELLE","BERCE","BETON","BIBLE","BICHE","BIDON","BIERE",
  "BIJOU","BILAN","BILLE","BISON","BLANC","BLASE","BLEUS","BLOND",
  "BOIRE","BOISE","BOMBE","BONNE","BONUS","BORDE","BOSSE","BOTTE",
  "BRAVE","BRISE","BRUME","BRUNE","BRUTE","BUCHE","BULLE",
  // C
  "CABLE","CACHE","CADRE","CADET","CALME","CANAL","CANNE","CARAT",
  "CARGO","CAUSE","CEDER","CEDRE","CERNE","CHAIR","CHAMP","CHANT",
  "CHAUD","CHENE","CHERI","CHIEN","CHOIX","CHOSE","CHUTE","CIDRE",
  "CITER","CIVIL","CLAIR","CLORE","COBRA","COCON","COEUR","COLLE",
  "COLON","CONGE","CONNU","CONTE","COPIE","COQUE","CORDE","CORNE",
  "CORNU","COTON","COUDE","COUPE","COURS","CRANE","CREER","CREME",
  "CRIER","CRISE","CROIX","CRUEL","CUIRE","CULTE","CUMIN","CYCLE",
  // D
  "DALLE","DANSE","DATER","DEBAT","DEBUT","DECOR","DELTA","DEMON",
  "DENSE","DEPOT","DESIR","DETTE","DEUIL","DIGUE","DINDE","DIVIN",
  "DOPER","DOREE","DOUCE","DOUZE","DRAME","DROIT","DRONE","DROLE",
  "DUPER","DUREE","DURER","DUVET",
  // E
  "ECART","ECLAT","ECHOS","ECRAN","ECRIN","EFFET","EGALE","ELEVE",
  "ELIRE","ELITE","ENFER","ENNUI","ENVIE","ENVOL","EPAIS","EPAVE",
  "EPICE","EPOUX","ERRER","ESSAI","ETAGE","ETAIN","ETALE","ETANG",
  "ETAPE","ETUDE","EVEIL","EXACT","EXCES","EXILE","EXODE","EXTRA",
  // F
  "FABLE","FAIRE","FARCE","FATAL","FAUNE","FAUTE","FEMME","FERME",
  "FIBRE","FICHE","FILET","FINAL","FINIR","FIXER","FLEUR","FLORE",
  "FOLIE","FONTE","FORCE","FORET","FORGE","FORME","FORUM","FOSSE",
  "FOULE","FOUET","FOYER","FRAIS","FRANC","FREIN","FRERE","FROID",
  "FRONT","FRUIT","FUGUE","FUMEE","FUSEE","FUTUR",
  // G
  "GAFFE","GALET","GANTS","GARDE","GARER","GAZON","GEANT","GELER",
  "GEMIR","GENIE","GENRE","GENOU","GERME","GESTE","GILET","GIVRE",
  "GLACE","GLOBE","GOMME","GORGE","GOSSE","GRACE","GRAIN","GRAND",
  "GRAVE","GREVE","GRISE","GUIDE","GUEPE",
  // H
  "HABIT","HACHE","HAINE","HALTE","HAMAC","HANTE","HARPE","HATER",
  "HAUTE","HERBE","HERON","HEROS","HETRE","HEURE","HIVER","HOMME",
  "HONTE","HOTEL","HUILE","HYMNE",
  // I
  "ICONE","IDEAL","IMAGE","INDEX","ISSUE",
  // J
  "JAMBE","JATTE","JAUNE","JETON","JEUDI","JEUNE","JOLIE","JOUER",
  "JOUET","JOUIR","JOURS","JURER","JUPON","JUSTE",
  // K
  "KARMA","KAYAK",
  // L
  "LABEL","LACET","LAINE","LAMPE","LANCE","LANDE","LAPIN","LAQUE",
  "LARGE","LARME","LASER","LATIN","LAVER","LEGAL","LEGER","LENTE",
  "LEVER","LEVRE","LIBRE","LIEGE","LIGUE","LILAS","LIMER","LINGE",
  "LISSE","LITRE","LIVRE","LOCAL","LOGER","LOTUS","LOUER","LOURD",
  "LOYAL","LUEUR","LUNDI","LUTTE","LYCEE",
  // M
  "MAFIA","MAGIE","MAINS","MAJOR","MALLE","MALIN","MAMAN","MANGE",
  "MARDI","MAREE","MARGE","MARIN","MASSE","MATCH","MATER","MATIN",
  "MAUVE","MECHE","MEDIA","MELEE","MELON","MERCI","MERLE","MESSE",
  "METAL","METRE","MEUTE","MICHE","MICRO","MIEUX","MIMER","MINCE",
  "MINER","MIXTE","MOINE","MOISI","MONDE","MONTE","MORAL","MORNE",
  "MORUE","MOTIF","MOULE","MULET","MURAL","MURER","MUTER","MYTHE",
  // N
  "NACRE","NAGER","NAIVE","NAINE","NAPPE","NATAL","NAVAL","NAVET",
  "NEIGE","NEVEU","NICHE","NOBLE","NOCES","NOEUD","NOIRE","NORME",
  "NOTER","NOTRE","NOUER","NOYAU","NOYER","NUAGE","NUIRE","NYLON",
  // O
  "OASIS","OBESE","OBEIR","OCEAN","ODEUR","OFFRE","OLIVE","OMBRE",
  "ONCLE","ONDES","OPERA","OPTER","ORAGE","ORGUE","ORNER","ORTIE",
  "OSIER","OTAGE","OUATE","OUBLI","OURLE","OUTRE","OUVRE","OVALE",
  "OXYDE",
  // P
  "PACTE","PAIRE","PALME","PANDA","PANEL","PANNE","PARCE","PARLE",
  "PARMI","PAROI","PARTI","PASSE","PATTE","PAUSE","PAYER","PEAGE",
  "PECHE","PEINT","PEINE","PELER","PELLE","PENTE","PERDU","PERLE",
  "PERTE","PESER","PETIT","PHARE","PHASE","PHOTO","PIANO","PIECE",
  "PIEGE","PINCE","PISTE","PIVOT","PIXEL","PLACE","PLAGE","PLAID",
  "PLANE","PLATE","PLEIN","PLIER","PLOMB","PLUIE","PLUME","POCHE",
  "POIDS","POINT","POIRE","POMME","POMPE","PORTE","POSER","POSTE",
  "POTIN","POUCE","POULE","PRIER","PRIME","PRISE","PROIE","PROSE",
  "PRUNE","PUNIR","PURGE",
  // Q
  "QUAND","QUEUE","QUOTA",
  // R
  "RADAR","RAIDE","RALER","RAMPE","RANGE","RAPER","RASER","RATER",
  "RAYER","RAYON","REBUT","RECIT","RECUL","REGAL","REGLE","REINE",
  "RENDU","RENTE","REPAS","REPOS","REVER","REVUE","RIDER","RIMER",
  "RIVAL","RIVER","ROCHE","RODER","ROMAN","RONCE","RONDE","ROUGE",
  "ROUTE","ROYAL","RUBAN","RUCHE","RUGBY","RUSER",
  // S
  "SABLE","SABOT","SACRE","SAINT","SALER","SALON","SALUT","SAMBA",
  "SANTE","SAPIN","SATIN","SAUCE","SAUGE","SAULE","SAUNA","SAUVE",
  "SCENE","SCIER","SECHE","SEIZE","SELLE","SEMER","SELON","SENSE",
  "SERIE","SERIN","SERRE","SEUIL","SIEGE","SIGNE","SINGE","SIROP",
  "SOBRE","SOCLE","SONDE","SORTE","SOUCI","SOUDE","SOUPE","SPORT",
  "STAGE","STORE","STYLO","SUAVE","SUBIR","SUCRE","SUEUR","SUITE",
  "SUJET","SUPER",
  // T
  "TABAC","TABOU","TABLE","TACHE","TAIRE","TALON","TANTE","TAPIS",
  "TARIR","TARTE","TASSE","TAUPE","TAXER","TEMPO","TENIR","TENTE",
  "TENUE","TERME","TERRE","TEXTE","THEME","THESE","TIERS","TIGRE",
  "TIRER","TISSU","TITRE","TOILE","TOISE","TOMBE","TONNE","TORDU",
  "TORSE","TOTAL","TOTEM","TRACE","TRAIN","TRAIT","TRAME","TREVE",
  "TRIBU","TRIER","TRONC","TROUS","TUILE","TURBO","TUYAU",
  // U
  "ULTRA","UNION","UNITE","USAGE","USINE","UTILE",
  // V
  "VACHE","VAGUE","VALET","VALVE","VALSE","VASTE","VEINE","VENIN",
  "VENIR","VENTE","VERBE","VERRE","VERSE","VERTU","VESTE","VIDEO",
  "VIDER","VIGNE","VILLA","VINGT","VIRAL","VISER","VITRE","VIVRE",
  "VOCAL","VOILE","VOLER","VOTER","VOUTE",
  // W
  "WAGON",
  // Z
  "ZESTE","ZONES",
];

// All valid guesses (includes answers + more words players might try)
export const VALID_GUESSES: Set<string> = new Set([
  ...ANSWERS,
  // Additional valid French 5-letter words players might try
  // A
  "ABOUT","ACHAT","ACTIF","AGENT","AGREE","AIGRE","AINES","AINSI",
  "ALGUE","ALLEE","ALORS","AMENE","AMPLE","ANTAN","APPUI","ARDUE",
  "ARIDE","ASILE","ATLAS","AUDIO","AVANT","ABOLI","ACCES","ACTES",
  "AGACE","AGITE","AHURI","AIEUX","ALITE","ALLIE","AMIES","AMPLI",
  "ANCHE","ANGES","ANIME","AORTE","APNEE","APPAT","ARMES","ASSEZ",
  "AUTEL","AUTAN","AUTOS","AUTRE","AVAIT","AVALE","AVONS","AVOUE",
  // B
  "BARIL","BARON","BADGE","BAGOU","BAHUT","BAIES","BAINS","BALSA",
  "BANCO","BANJO","BARBU","BARGE","BASES","BEAUF","BEBES","BEGUE",
  "BELGE","BENNE","BERGE","BETES","BINER","BLEME","BLITZ","BLUES",
  "BOCAL","BOITE","BONDS","BORDS","BOUGE","BOULE","BOUSE","BOUTS",
  "BREFS","BRINS","BROCS","BROIE","BRUNS","BUEES","BUTER","BUTIN",
  "BUTTE",
  // C
  "CABAS","CABRI","CACAO","CAFES","CAGES","CALER","CAMES","CAMPE",
  "CANIF","CANOE","CAPOT","CARPE","CARTE","CASER","CASTE","CAVES",
  "CEINT","CELUI","CENNE","CESSE","CHALE","CHAPE","CHARS","CHATS",
  "CHAUX","CHEFS","CHOIR","CIELS","CIEUX","CIMES","CIRES","CLANS",
  "CLEFS","CLIPS","CLOSE","CLUBS","CODES","COING","COITE","COLIS",
  "COMME","COMTE","CONDO","CONES","CORPS","COSSE","COTER","COTTE",
  "COUPS","COURT","COUTS","CRABE","CREUX","CREVE","CRIME","CRINS",
  "CROSS","CUBES","CUIRS","CUITS","CULOT","CURER","CUVEE",
  // D
  "DAIMS","DAMES","DEBIT","DECIS","DECUE","DEFIS","DEGRE","DELIE",
  "DEMIS","DENIM","DEPIT","DERBY","DEVIN","DEVIS","DIETE","DINGO",
  "DIODE","DITES","DIVAN","DOCKS","DOGME","DOIGT","DONNA","DORIS",
  "DORMI","DOSEE","DOTER","DOUAI","DOUTE","DRAPS","DUELS","DUNES",
  "DUPES","DURES",
  // E
  "EDILE","ELANS","EMAIL","EMPLI","ENCAS","ENCRE","ENGIN","ENTRE",
  "ENVOI","EPARS","EPATE","EPEES","EPINE","EPRIS","ERGOT","ESSOR",
  "ETAIS","ETANT","ETATS","ETEND","ETIRE","ETRES","ETUVE","EUROS",
  "EVADE","EVITE","EXIGE","EXILS",
  // F
  "FACES","FAGOT","FAIMS","FAITS","FANEE","FANON","FARDS","FASTE",
  "FAUVE","FEINS","FELIN","FEMUR","FERAI","FESSE","FETAL","FETES",
  "FEVES","FIEFS","FIERE","FIGES","FILMS","FILOU","FINIE","FIRME",
  "FIXEE","FLAIR","FLANC","FLICS","FLIRT","FLOTS","FLUET","FLUTE",
  "FOCAL","FOINS","FONCE","FONDS","FORTS","FOUIR","FOURS","FRIGO",
  "FRIME","FRIPE","FRISE","FRITE","FUIES","FUMER","FURET","FUSIL",
  "FUTON",
  // G
  "GAGES","GAINS","GALAS","GALES","GALOP","GAMME","GANGS","GARCE",
  "GARNI","GATER","GAULE","GAVEE","GAZER","GELEE","GEMIE","GENES",
  "GERER","GIFLE","GIRON","GITES","GLANS","GNOME","GODET","GOLFE",
  "GOUGE","GOULU","GOURD","GOUTS","GRADE","GRENU","GRILL","GRIMP",
  "GROOM","GRUAU","GRUME","GUERI","GUETS","GUISE",
  // H
  "HAIES","HALER","HALLS","HAMPE","HARAS","HARDI","HAREM","HAUTE",
  "HAVRE","HENNE","HEROS","HEURT","HONTE","HORDE","HOULE","HUEES",
  "HUMEE","HUMUS","HUPPE","HYDRE","HYPER",
  // I
  "IDEES","IGLOO","ILOTS","IMPIE","IMPOT","INFOS","ITEMS",
  // J
  "JABLE","JALOU","JAPAN","JASPE","JAUGE","JAVEL","JEANS","JETEE",
  "JETES","JOIES","JOINS","JOINT","JOKER","JOUEE","JOULE","JUMBO",
  "JUNTE","JUPES","JUREE","JURES","JURON","JUTEE","JUTES",
  // K
  "KAKIS","KAPOK","KARST","KEBAB","KHAKI","KILOS","KIWIS","KOALA",
  "KRAFT","KRACH",
  // L
  "LABRE","LACIS","LAGON","LAIDS","LAIES","LAITE","LAITS","LAMAS",
  "LAMEE","LAMER","LANGE","LAQUE","LARDS","LARVE","LASSE","LATEX",
  "LATTE","LEADS","LEDIT","LEMUR","LEPRE","LESTE","LEURS","LEVES",
  "LIANE","LIANT","LIARD","LIBRA","LIENS","LIFTS","LIGNE","LIMBE",
  "LIMON","LINER","LIONS","LISTE","LIVRA","LOBER","LOBES","LOESS",
  "LOFTS","LOGOS","LOIRS","LOOKS","LOPIN","LOTIR","LOUEE","LOUPE",
  "LOVER","LUCID","LUGES","LUIRE","LUNES","LUPUS","LUTHS","LUXER",
  "LYRES",
  // M
  "MACHO","MACRO","MADRE","MAGMA","MAGOT","MAINT","MAIRE","MALES",
  "MALTE","MANDE","MANES","MANIE","MANIF","MANTE","MARCS","MARES",
  "MARNE","MARTE","MASQU","MATHS","MATOS","MAURE","MAYAS","MEDAL",
  "MEDIE","MEMES","MENAS","MENEE","MENER","MENUS","MERIS","METHS",
  "MEURT","MIELS","MIENS","MIGRE","MILLE","MIMES","MINAS","MINEE",
  "MINES","MINIS","MINUS","MIRES","MISES","MITES","MITRE","MIXER",
  "MOCHA","MODAL","MODES","MOGOL","MOINS","MOITE","MOLES","MOLLO",
  "MONKS","MONTS","MORDS","MORTS","MORVE","MOTEL","MOTTE","MOUDS",
  "MOUES","MOULA","MOULT","MOUDS","MUETS","MUFLE","MUGIR","MUONS",
  "MURES","MURIS","MUSCS","MUSEE","MUSER","MUTEE","MYOPE",
  // N
  "NADIR","NANTI","NARCO","NARDS","NASES","NAZIS","NEONS","NERDS",
  "NERFS","NETTE","NEUFS","NIAIS","NIDAL","NIERA","NIVAL","NODAL",
  "NOIRS","NOMMA","NONCE","NONNE","NORIA","NOTAI","NOTEE","NOTES",
  "NOUER","NOVAU","NOYEE","NUEES","NUISE","NUITS","NULLE","NURSE",
  // O
  "OBIER","OBOLE","OCRES","OCTET","ODEON","OEUFS","OISIF","OMEGA",
  "OPIUM","ORALE","ORAUX","ORIEL","ORMES","ORNEE","OSCAR","OUAIS",
  "OUIES","OURLE","OURSI","OVINS",
  // P
  "PAGES","PAIEN","PALIS","PALOT","PAMPA","PANES","PANTS","PAPAS",
  "PAPES","PARCS","PARES","PARIS","PARTS","PARUS","PASTA","PATCH",
  "PATER","PATIR","PATIO","PATRE","PEAUX","PENAL","PENDS","PENDU",
  "PENNE","PEPIN","PERES","PERIT","PERSO","PESOS","PETAL","PETER",
  "PETON","PEULS","PICKS","PIEDS","PIERS","PIEUX","PIGER","PILAF",
  "PILES","PILON","PILOT","PINES","PINOT","PINTA","PIONS","PIPES",
  "PIQUE","PITRE","PIZZA","PLANS","PLANT","PLATS","PLEBE","PLEUR",
  "PLIEE","PLIES","PLOTS","POETE","POILS","POLIR","POLOS","PONTS",
  "POPES","PORTS","POSES","POTEE","POUFS","POULS","PREAU","PRELE",
  "PREND","PRETS","PREVU","PRIVA","PRIMO","PRIVE","PROFS","PROMO",
  "PROTE","PRUDE","PUBIS","PUCES","PUISE","PULLS","PULPE","PUNIS",
  "PURIN",
  // Q
  "QUAIS","QUASI","QUELS",
  // R
  "RACES","RADIS","RAFLE","RAGES","RAGOT","RAIES","RAILS","RAMAS",
  "RAMEE","RAMES","RANCH","RANGS","RAPES","RASEE","RATEL","RATES",
  "RATIO","RATON","RAVIE","RAVIN","RAVIS","REBAB","REBAT","REBUS",
  "RECEL","REDIS","REFUS","REGIE","REGIS","REGNA","REINS","REJET",
  "RELAI","RELAX","REMIS","RENAL","RENDS","RENIE","RENOM","REPUE",
  "RESTA","RETIF","RETRO","REUNI","RIAIT","RIEUR","RIFLE","RIMES",
  "RIPOU","RISEE","RITES","RIVES","RIVET","ROBES","ROBIN","ROBOT",
  "ROLES","RONGE","ROSES","ROSIR","ROTIS","ROUES","ROUET","ROUIR",
  "ROULE","RUADE","RUBIS","RUDES","RUEES","RUGIR","RUMBA","RUNES",
  "RURAL","RUSEE","RUSSE",
  // S
  "SABRE","SAFES","SAGAS","SAGES","SAHEL","SAINS","SALIR","SALSA",
  "SALUE","SALVE","SAPIN","SAROS","SATIN","SAUTE","SAVEZ","SEAUX",
  "SECTE","SEINS","SEMEE","SEMIS","SENNE","SENTI","SEPIA","SERAS",
  "SERGE","SERIF","SERPE","SERVE","SEULS","SEVIR","SIEUR","SIGMA",
  "SILEX","SILOS","SINUS","SIRES","SITES","SOINS","SOLDE","SOLES",
  "SOMME","SONNE","SONGE","SORTS","SORTI","SOUDS","SOURI","STADE",
  "STAND","SUCEE","SUEES","SUITE","SUJET","SUMAC","SURGE","SUSHI",
  // T
  "TABIS","TACET","TACLE","TACOS","TACOT","TACTS","TAIRE","TALER",
  "TANKS","TANTE","TAONS","TAPAS","TAPEE","TAPER","TARES","TARIN",
  "TAROT","TATER","TEINT","TEMPS","TENDS","TENDU","TENON","TENOR",
  "TESTS","TETES","TIGHT","TILDE","TOAST","TOGES","TOITS","TOKEN",
  "TOMBA","TOMES","TONAL","TONDS","TONER","TONGS","TOQUE","TOURS",
  "TROUE","TUBES","TULIP","TURFS",
  // U
  "UBACS","UKASE","UMAMI","UNIES","URINE","USUEL","USURE",
  // V
  "VAGIR","VAINS","VANNE","VANTE","VAREC","VASES","VEAUX","VECUE",
  "VELUE","VELUM","VENDS","VENDU","VENUS","VERDI","VERGE","VERIN",
  "VERNI","VERRA","VERTS","VEXER","VIAND","VICES","VIENS","VIGIL",
  "VILES","VINEE","VINYL","VIOLE","VIRAI","VIREE","VIRES","VIRUS",
  "VISAS","VISEE","VISON","VITAL","VITES","VIVAT","VIVES","VIVRA",
  "VOEUX","VOICI","VOILA","VOTRE","VOUEE","VOUER","VOULU","VOYEZ",
  "VRAIE","VRAIS",
  // W-Z
  "ZONAL","ZONER","ZOUKS","ZINCS","ZEBRA",
]);

// Legacy exports for backwards compat
export const WORDS = [...VALID_GUESSES];
export const ANSWER_POOL = ANSWERS;
